POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "ChatGPT",
    "author": "Bing",
    "url": "http://google.com",
    "likes": 3
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Missing Like",
    "author": "Lissing Mike",
    "url": "http://google.com"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "I have a user",
    "author": "who is my author",
    "url": "http://google.com"
}
